### ISSUE TITLE
3.1.  Análisis de Riesgos

### ISSUE THREAD

**Issue by buitrago001** [ISWPOLI/Poli-antifraude#10]
Realizar el análisis de riesgos según la metodología Scrum:

- [x] Lista @Basespoli 
- [x] Evaluación P/I  @Basespoli 
- [x] Gráfica @Basespoli 
- [x] Evaluación gráfica / Planes y acción @Basespoli 
- [x] Reevaluación Evaluación P/I  @Basespoli 
- [x] Replantear Gráfica @Basespoli

**Comment by ghost** [comment]
Tarea pendiente en analisis

**Comment by ghost** [comment]
El análisis de riesgos fue subido al repositorio.

https://github.com/ISWPOLI/Poli-antifraude/blob/master/Documentacion/2%20Planeaci%C3%B3n/Risk%20PoliAntifraude.xlsx

**Comment by ghost** [comment]
Se realizan las correcciones indicadas por el docente: 
La gráfica no corresponde a la comparación entre probabilidad impacto. Los planes no tienen evaluación de probabilidad impacto solo los riesgos. No se realiza re-evaluación. Solo los riesgos altos y medios ameritan la evaluación del plan.

**Comment by ghost** [comment]
Se realiza las correcciones indicadas y se sube el documento al repositorio.

https://github.com/ISWPOLI/Poli-antifraude/blob/master/Documentacion/2%20Planeaci%C3%B3n/Risk%20PoliAntifraude%20V2.xlsx

**Comment by ghost** [comment]
Se realiza socialización con equipo de trabajo y cierre de tarea.
