### ISSUE TITLE
3. Estimación de tiempo, desarrollo y codificación CRUD entidades

### ISSUE THREAD

**Issue by ghost** [ISWPOLI/Poli-antifraude#12]
-[ ] Cree la plantilla para la estimación y estime los tiempos para:
     - Ingreso genérico a un sistema “validación de usuarios y contraseña”: (CRUD asociado)
     - Utilice 3 Roles con distintas vistas según la jerarquía.
     - Función de recuperación de clave (mediante el uso del correo).
-[ ] Desarrolle y registre los tiempos.
-[ ] Compare y concluya.

**Comment by buitrago001** [comment]
Tarea de clase independiente del sistema en desarrollo
