### ISSUE TITLE
Estructura de Desglose del Sistema

### ISSUE THREAD

**Issue by sebasc91** [ISWPOLI/Poli-antifraude#16]

**Comment by sebasc91** [comment]
Se entrega documento con el EDT del proyecto

**Comment by buitrago001** [comment]
- [x] Asignar tareas en el EDT a cada miembro del grupo(por nombre o asignacion por color) @sebasc91

**Comment by sebasc91** [comment]
Se inicia corrección del documento inicial de acuerdo a observaciones realizadas.

- [x] Desglose por tareas, según las actividades

**Comment by sebasc91** [comment]
Se realiza entrega de la corrección del EDT del proyecto de acuerdo a comentarios realizados

https://github.com/ISWPOLI/Poli-antifraude/blob/master/Documentacion/2%20Planeaci%C3%B3n/EDT-POLI%20ANTIFRAUDE%20V2.png

**Comment by sebasc91** [comment]
Se revisa y se aprueba el documento por el equipo de trabajo
