### ISSUE TITLE
5. History Mapping

### ISSUE THREAD

**Issue by ingenieriadelsoftware** [ISWPOLI/Poli-antifraude#2]
Desarollo de historias de usuario

**Comment by alejandro995** [comment]
Revisar los posibles temas relacionados con las historias de usuario, entrega el martes

**Comment by ghost** [comment]
Se consolida entrega final de historias de usuario teniendo en cuenta 4 tareas épicas , y las contribuciones del docente Diego Oliveros.

[Historias Usuario PoliAntifraude.xls.xlsx](https://github.com/ISWPOLI/Poli-antifraude/files/792249/Historias.Usuario.PoliAntifraude.xls.xlsx)

**Comment by buitrago001** [comment]
**Definir historias de usuario y History Mapping **

- [x] Definir de Historias épicas de usuario y su descripción. @sebasc91 Basespoli
- [x] Definir Característica (spin) y su descripción @sebasc91 Basespoli
- [x] Definir Criterios de Aceptación y su descripción @alejandro995 @buitrago001

https://docs.google.com/spreadsheets/d/1UNMSt6YRUsN0WiFQQvBvgYTcmv2wRdGDDceM1cK79K8/edit?usp=sharing

Nota recordar que horizontal se maneja tiempo y vertical alcance.
-[ ] Diagrama History Mapping.
http://moodlep17a.mipoli.co/pluginfile.php/58380/mod_resource/content/1/Plantilla%20historyMapping_.pdf

**Comment by buitrago001** [comment]
- [ ] Crear el user history map

**Comment by buitrago001** [comment]
[history map.pdf](https://github.com/ISWPOLI/Poli-antifraude/files/815626/history.map.pdf)

**Comment by buitrago001** [comment]
- [x] Revision de historias de usuario @buitrago001

- [x] Actualizacion del formato y presentacion @buitrago001

**Comment by buitrago001** [comment]
Se completa la revisión y actualización correspondiente se agrega formato al repositorio

https://github.com/ISWPOLI/Poli-antifraude/blob/Documentaci%C3%B3n/Documentacion/2%20Planeaci%C3%B3n/history%20mapping.pdf
