### ISSUE TITLE
Tomar secuencia de fotos

### ISSUE THREAD

**Issue by alejandro995** [ISWPOLI/Poli-antifraude#37]
Rol: Como un administrador de seguridad de la universidad PG.
Funcionalidad: Necesito que tome secuencia de fotos con el sistema de seguridad Poli Antifraude.
Resultado : Con la finalidad de almacenar en un sistema para poder hacer validaciones posteriores.

**Comment by buitrago001** [comment]
- [x] Implementacion y despliegue en el backend del modulo para activar la camara

- [x] Implementacion y despliegue en el backend del modulo para la toma de las secuencias fotograficas
