### ISSUE TITLE
Problemas con conection a la base de datos mySQL utilizando Auth0

### ISSUE THREAD

**Issue by alejandro995** [ISWPOLI/Poli-antifraude#4]
Aunque siguiendo la guia de Auth0 https://auth0.com/docs/connections/database/mysql no permite hacer la conexion a la base de datos local, mientras tanto se hace la conexion a la base de datos que tiene por defecto auth0.

**Comment by buitrago001** [comment]
se revisa tarea y se cierra ya que se realizo una nueva estructura del aplicativo donde no se genero este error
