### ISSUE TITLE
Generar preguntas de seguridad

### ISSUE THREAD

**Issue by alejandro995** [ISWPOLI/Poli-antifraude#40]
Rol: Como un administrativo de la universidad PG.
Caracteristica/Funcionalidad: Necesito que el sistema poli Antifraude me genere preguntas de seguridad personalizadas
Razon/Finalidad: Con la finalidad de poder hacer un reconocimiento de la persona mediante uso de su informacion personal.

**Comment by buitrago001** [comment]
- [x] Script DB con las preguntas de seguridad
