### ISSUE TITLE
DB dummi con preguntas y respuestas

### ISSUE THREAD

**Issue by alejandro995** [ISWPOLI/Poli-antifraude#41]
Rol: Como un DBA.
Caracteristica/Funcionalidad: Necesito que me almacene un banco de preguntas y respuestas.
Razon/Resultado: Con la finalidad de verificar la identidad de la persona.

**Comment by buitrago001** [comment]
- [x] Script de la BD con preguntas para el registro de información personal

- [x] query a la DB para validar respuestas con información personal o de registro

**Comment by buitrago001** [comment]
se completan los scripts y se cargan al repositorio
