### ISSUE TITLE
Integrarse con el sistema epic

### ISSUE THREAD

**Issue by alejandro995** [ISWPOLI/Poli-antifraude#44]
Rol: Como un administrativo de la universidad PG.
Característica / Funcionalidad: Necesito que el sistema me permita integrarse con el sistema de epic
Razón / Resultado: Con la finalidad de que el estudiante de modalidad virtual presente sus examenes a traves de la plataforma epic y sea monitoreado

**Comment by buitrago001** [comment]
Se cierra milestone debido al cambio del sistema epic al sistema canvas
