### ISSUE TITLE
Tomar Foto inicial

### ISSUE THREAD

**Issue by alejandro995** [ISWPOLI/Poli-antifraude#48]
Rol: Como un administrativo de la universidad PG.
Característica / Funcionalidad: Necesito que el sistema tome una foto al iniciar el examen despues de haber contestado las preguntas de seguridad y aceptado el comunicado legal.  
Razon/ Resultado: Con la finalidad de obtener la foto de referencia para asi hacer la comparacion de imagenes.

**Comment by buitrago001** [comment]
issue repetida, tarea cubierta con issue #47
