### ISSUE TITLE
Guardar Imagenes

### ISSUE THREAD

**Issue by alejandro995** [ISWPOLI/Poli-antifraude#50]
Rol: Como un administrativo de la universidad PG.
Característica / Funcionalidad: Necesito que el sistema guarde las imagenes tomadas en la base de datos.
Razon/ Resultado: Con la finalidad de acceder a esa informacion en cualquier tipo de reclamacion o para verificar.

**Comment by buitrago001** [comment]
- [x] script de BD para guardar imagen del estudiante

- [x] script de BD para guardar una id de evaluación y asociar con el id del estudiante y la materia
