### ISSUE TITLE
Tabla de imagenes 

### ISSUE THREAD

**Issue by alejandro995** [ISWPOLI/Poli-antifraude#52]
Rol: Como herramienta poli-anti.
Característica / Funcionalidad: Necesito que el sistema tenga una tabla donde se puedan alamcenar las imagenes tomadas.
Razon/ Resultado: Con la finalidad de tener pruebas e informacion acerca del proceso que realizo el estudiante.

**Comment by buitrago001** [comment]
- [x] array de imagenes con un delay entre cada imagen para poder compararlas @alejandro995

**Comment by alejandro995** [comment]
https://186.155.26.16/camera Se agrega el link externo de la camara y el arrelgo
