### ISSUE TITLE
Comparar Imagenes

### ISSUE THREAD

**Issue by alejandro995** [ISWPOLI/Poli-antifraude#55]
Rol: Como herramienta poli-anti.
Característica / Funcionalidad: Necesito que el sistema compare la fotos tomadas.
Razon/ Resultado: Con el fin de verificar que la persona que se encuentre en la primera image no haya echo suplantacion (fraude academico).

**Comment by buitrago001** [comment]
se cierra milestone ya que se encuentra repetido
