### ISSUE TITLE
Obtener Informacion para Preguntas

### ISSUE THREAD

**Issue by alejandro995** [ISWPOLI/Poli-antifraude#58]
**Rol:**    Como Administrador 
**Característica / Funcionalidad:** 
Necesito que el sistema obtenga la información del estudiante de la base de datos externas 
**Razon/ Resultado:** 
Con el fin de crear preguntas y respuestas.

**Comment by ghost** [comment]
Se evaluó con Alvaro Quiroga, para tener acceso externo a los dominios del politécnico para poder obtener esta información, pero nos indico que como en este acceso hay mucha información sensible tanto para el campus como para sus clientes "Estudiantes", se requiere elevar para que nos otorguen los permisos y poder obtener esta información, Adicional Alvaro Quiroga nos propone poder sacar la información de las bodegas de datos directamente, pero también se requiere de permisos,  está pendiente reunión con Fabian Devia, Alvaro Quiroga por disponibilidad de agenda.

**Comment by ghost** [comment]
Se determina que no se requiere conexión a bases externas ya que el funcionamiento se realizará en  un servidor local en el cual se realizarán las pruebas funcionales y el despliegue, seguido a esto se incrustara la aplicación en los servidores de la universidad donde se conectará con la bases actuales no se tiene errores de conexión a bases ya que se usa el mismo modelo ER que la universidad tiene para el almacenamiento de sus datos.
