### ISSUE TITLE
Mostrar vista de preguntas.

### ISSUE THREAD

**Issue by alejandro995** [ISWPOLI/Poli-antifraude#59]
Rol: Como Administrador del PG
Característica / Funcionalidad: Necesito que el sistema muetre la preguntas de seguridad y que el estudiante pueda responder a esas preguntas desde la misma pagina al comienzo y al final del proceso evaluativo. 
Razon/ Resultado: Con el fin de obtener la informacion de validacion.

**Comment by buitrago001** [comment]
Se cierra tarea ya que esta duplicada en la tarea #40
