### ISSUE TITLE
Generar tabla de pregunta y respuesta

### ISSUE THREAD

**Issue by alejandro995** [ISWPOLI/Poli-antifraude#62]
**Rol:**    Como Administrador del PG
**Característica / Funcionalidad:** 
Necesito que el sistema tenga una tabla en la base de datos donde se almacenen las preguntas y respuestas realizadas por el el sistema al estudiante. 
**Razon/ Resultado:** 
Con el fin de verificar de tener la información archivada para revisión, reporte y comprobación.

- [x] Definir estructura de preguntas y respuestas y cómo enlazarlas.

- [x] Definir los datos que se requieren persistir con el equipo de trabajo.

- [x]  Crear la tabla de preguntas y de respuestas con la estructura socializada.

**Comment by ghost** [comment]
Se crea la base para almacenar las preguntas en la base PoliAntifraude la misma base que se está manejando, en la tabla preguntasIdentificacion donde se tiene
       Campo	Tipo	Cotejamiento	 Nulo Predeterminado	Extra	
	idPreg	int(5) utf8_general_ci No	 None	AUTO_INCREMENT, como primera fase, se esta terminando la batería de preguntas para poder determinar si el ER escogido se acomoda a la necesidad,

[PreguntasIdentificacionV(1).zip](https://github.com/ISWPOLI/Poli-antifraude/files/950589/PreguntasIdentificacionV.1.zip)

**Comment by ghost** [comment]
Se crea la tabla **respuestasIdentificacion** donde se podrá almacenar las respuestas del estudiante con la siguiente estructura: 

![image](https://cloud.githubusercontent.com/assets/25758763/25358205/4397549a-2906-11e7-8e64-88a1b7e639fe.png)

**Comment by ghost** [comment]
Se sube la primer versión de la tabla  **respuestasIdentificacion** donde se definieron los siguientes campos con el equipo de trabajo: 

id como llave de campo, Codigo para relacionar al estudiante con su respuesta, **idPreg** donde se identifica la pregunta para poder tener una medición, y la respuesta que genera el estudiante.

[respuestasIdentificacion V(1).zip](https://github.com/ISWPOLI/Poli-antifraude/files/953120/respuestasIdentificacion.V.1.zip)

**Comment by ghost** [comment]
Se crea la tabla **preguntasidentificacion** donde se podrá almacenar la batería de preguntas del estudiante con la siguiente estructura:

![image](https://cloud.githubusercontent.com/assets/25758763/25359182/cd9d5772-2909-11e7-812a-92dadfb67513.png)

**Comment by ghost** [comment]
Se socializa la estructura del cuestionario, y los datos a persistir en la base, se llega a un acuerdo con el equipo, los product Owner y los Scrum master  se realiza la creación de las bases asociadas, se hacen pruebas funcionales y cierre.
