### ISSUE TITLE
Vista de comunicado

### ISSUE THREAD

**Issue by alejandro995** [ISWPOLI/Poli-antifraude#64]
Rol: Como Administrador del PG
Característica / Funcionalidad: Necesito que el sistema muestre un comunicado antes generar las preguntas de seguridad y tomar las fotos.
Razon/ Resultado: Con el fin de informar que derechos y deberes debe cumplir , la finalidad del proceso y acepte sus terminos y condiciones .

**Comment by buitrago001** [comment]
se cierra milestone ya que esta tarea fue asignada en otro milestone
