### ISSUE TITLE
Ventana emergente, "terminos y condiciones"  y "tratamiento de datos"

### ISSUE THREAD

**Issue by alejandro995** [ISWPOLI/Poli-antifraude#65]
Rol: Como Administrador del PG
Característica / Funcionalidad: Necesito que el estudiante pueda aceptar a el comunicado. 
Razon/ Resultado: Con el fin de proceder con el proceso de validacion.

**Comment by buitrago001** [comment]
- [x] Se genera JS para la generación de una ventana emergente con el fin de mostrar términos de uso y tratamiento de datos para proceder con el sus del modulo propuesto @buitrago001
