### ISSUE TITLE
Acceder a datos externos

### ISSUE THREAD

**Issue by alejandro995** [ISWPOLI/Poli-antifraude#66]
Rol: Como Administrador del PG
Característica / Funcionalidad: Necesito que el sistema pueda conectarse a diferentes sistemas o bases de datos que utiliza la universidad.
Razon/ Resultado: Con el fin de trabajar con los mismos datos.

**Comment by buitrago001** [comment]
- [x] Se revisa viabilidad de acceder a los datos a datos externos con el fin de garantizar el acoplamiento a otros servicios diferentes al politécnico Grancolombiano @buitrago001

**Comment by buitrago001** [comment]
sistema tendrá la capacidad de adaptarse a la infraestructura del cliente con generando un mínimo de cambios dentro de su estructura de código, se realizan pruebas sobre base dummi generada dentro del proyecto
