### ISSUE TITLE
Obtener informacion

### ISSUE THREAD

**Issue by alejandro995** [ISWPOLI/Poli-antifraude#67]
**Rol:**    Como Administrador del PG

**Característica / Funcionalidad:** 
Necesito obtener la información de las base de datos externas y completar las bases de datos locales para poder realizar los procesos de validación. 

**Razon/ Resultado:**
Con el fin de tener los datos de estudiante, Codigo, cédula, Fecha nacimiento, corte, periodo, semestre y demás que puedan relacionarse con el id del estudiante (código).

**Comment by ghost** [comment]
Se evaluó con Alvaro Quiroga, y Steve para tener acceso obtener esta información, donde nos dan una solución más viable, donde la aplicación esté interna y se realicen consultas por medio de servicios que sean respondidas por el FrontEnd y de este modo se puede hacer el puenteo para la comunicación sin embargo,  este acceso cuenta con mucha información sensible tanto para el campus como para sus clientes "Estudiantes", se requiere elevar para que nos otorguen los permisos y poder obtener esta información, está pendiente reunión con Fabian Devia, Alvaro Quiroga y steve por disponibilidad de agenda.

**Comment by ghost** [comment]
Se determinó que no es necesario tener una estructura de conexión externa a bases de datos ya que las pruebas funcionales y el despliegue se hará en un servidor local.
