### ISSUE TITLE
Tablas registro estudiante y registro de padres

### ISSUE THREAD

**Issue by alejandro995** [ISWPOLI/Poli-antifraude#68]
**Rol:**    Como Administrador del PG
**Característica / Funcionalidad:** 
Necesito que toda información externa obtenida sea almacenada en una base de datos dedicada para la herramienta. 
**Razon/ Resultado:** 
Con el fin de tener un backup, mejorar rendimiento y proveer reportes sin necesidad de conexión a datos externos.

**Comment by ghost** [comment]
Se sube la primer versión de la base de datos, con el modelo ER actual del poli para almacenamiento de información general, se crea una base con nombre poliAntifraude y una tabla de registroestudiante siguiendo la estructura deseada. 

[registroestudiante V(1).zip](https://github.com/ISWPOLI/Poli-antifraude/files/950556/registroestudiante.V.1.zip)

**Comment by buitrago001** [comment]
- [x] Edicion de los scripts de las bases de datos de registro estuiante y se agrega registro de padres
Poli-antifraude/Implementacion/BBDD V1/registroestudiante V(1) Insercion.sql

**Comment by buitrago001** [comment]
se generan actualizaciones basados en cambios recientes dentro de la planeacion y spints
