### ISSUE TITLE
Almacenar Datos

### ISSUE THREAD

**Issue by alejandro995** [ISWPOLI/Poli-antifraude#69]
**Rol:**      Como Administrador del PG
**Característica / Funcionalidad:** 
Necesito almacenar todos los datos obtenidos de las otras bases de datos en la base "local".
**Razon/ Resultado:** 
Con el fin de tener uns respaldo de la información. 

- [x] Crear la BBDD para el almacenamiento de datos.

- [x] Definir los datos a persistir con el equipo de trabajo.

- [x] Hacer pruebas funcionales de crear, insertar, eliminar y acoplar datos.

**Comment by ghost** [comment]
El almacenamiento de datos se propone en la base actual PoliAntifraude para cualquier información, y con respaldo local, la base se crea en mySql,  según los modelos ER ya estructurados que tiene la universidad PG.

[registroestudiante V(1).zip](https://github.com/ISWPOLI/Poli-antifraude/files/950560/registroestudiante.V.1.zip)

**Comment by ghost** [comment]
Se indican los campos hasta el momento definidos de utilidad para la versión inicial, donde se contemplan Datos del estudiante, datos de la universidad que identifican al estudiante, y datos del estudiante que lo identifican como ciudadano de los cuales almacenaremos los necesario y crearemos preguntas para poder saber su identidad. 


![image](https://cloud.githubusercontent.com/assets/25758763/25354754/dbae7126-28f9-11e7-9090-378c496c8024.png)

**Comment by ghost** [comment]
Se realiza la primer inserción de la base sin ningún problema, se aclara que únicamente son datos personales por la sensibilidad de los mismos.

![image](https://cloud.githubusercontent.com/assets/25758763/25355272/a434e21e-28fb-11e7-92f4-7689aa5cb039.png)

**Comment by ghost** [comment]
Se sube la base con inserción de datos para verificación por parte del grupo, Scrum master y del product Owner.

[registroestudiante V(1) Insercion.zip](https://github.com/ISWPOLI/Poli-antifraude/files/952910/registroestudiante.V.1.Insercion.zip)

**Comment by ghost** [comment]
Se realiza la verificación de las pruebas funcionales e integración  con el desarrollo donde se acopla de modo correcto se realiza cierre.
