### ISSUE TITLE
Enviar informacion al Front-End

### ISSUE THREAD

**Issue by alejandro995** [ISWPOLI/Poli-antifraude#70]
Rol: Como Herramieta poli-antifraude
Característica / Funcionalidad: Necesito que el sistema pueda enviar todos los procesos realizados al front end para ser visualizado y administrados por funciones del front-end. 
Razon/ Resultado: Con el fin de tener un correcto funcionamiento de la herramienta. 

Generación de las vistas del frond end:

- [x] Vista autenticación @sebasc91
- [x] Vista Menú Principal @sebasc91
- [x] Vista recuperar contraseña

**Comment by sebasc91** [comment]
Se realiza entrega de la vista de autenticación, para el proyecto.

https://github.com/ISWPOLI/Poli-antifraude/blob/master/Implementacion/BBDD%20V1/Proyecto.zip

**Comment by sebasc91** [comment]
Se realiza entrega de la vista de recuperar contraseña, para el proyecto.

https://github.com/ISWPOLI/Poli-antifraude/upload/master/Implementacion/BBDD%20V1

**Comment by sebasc91** [comment]
Se realiza entrega de vista principal

**Comment by sebasc91** [comment]
#70 Se cierra tarea, entregada
