### ISSUE TITLE
Generar queries

### ISSUE THREAD

**Issue by alejandro995** [ISWPOLI/Poli-antifraude#72]
**Rol:**     Como Administrador del PG
**Característica / Funcionalidad:** 
Necesito que el sistema tenga un ORM que administre las consultas realizadas por usuarios de la herramienta. 
**Razon/ Resultado**:
 Con el fin de organizar los procesos que se realizan a la base de datos.

**Comment by buitrago001** [comment]
se cierra issue ya que se realizo el breakdown y se asigno a tareas especificas dentro de la generación de las bases de datos y los scripts de consulta dentro del código
