### ISSUE TITLE
Asignar proceso diciplinario

### ISSUE THREAD

**Issue by alejandro995** [ISWPOLI/Poli-antifraude#75]
Rol: Como Administrador del PG
Característica / Funcionalidad: Necesito que el sistema permita poder comenzar un proceso diciplinario con el estudiante desde la  vista de reportes. 
Razon/ Resultado: Con el fin de informar al estudiante que ha cometido una falta de fraude academico.

**Comment by buitrago001** [comment]
Tarea pendiente para validar si va a ser parte inicial del sistema a entregar

**Comment by buitrago001** [comment]
se cierra issue ya que no es parte del scope del proyecto
