### ISSUE TITLE
Información estudiante para simular el sistema

### ISSUE THREAD

**Issue by alejandro995** [ISWPOLI/Poli-antifraude#76]
Rol: Como Administrador del PG
Característica / Funcionalidad: Necesito que el sistema despues de comenzar un proceso diciplinario que actualize la informacion en todas las bases relacionas con el estudiante. 
Razon/ Resultado: Con el fin de que todos los entes de la universidad tenga acceso a esa informacion.

**Comment by buitrago001** [comment]
- [x] Script para la creacion del DB dummie con la informacion del estudiante

- [x] Llenado de tablas del DB
