### ISSUE TITLE
Tabla de proceso diciplinarios

### ISSUE THREAD

**Issue by alejandro995** [ISWPOLI/Poli-antifraude#77]
Rol: Como Administrador del PG
Característica / Funcionalidad: Necesito que el sistema tenga una tabla en la cual pueda identificar los procesos diciplinarios. 
Razon/ Resultado: Con el fin de tener un resplado de la informacion obtenidad por la herramienta.

**Comment by buitrago001** [comment]
se cierra issue ya que la función no sera implementada, sale del scope del proyecto
