### ISSUE TITLE
3. Levantamiento de requerimientos del sistema.

### ISSUE THREAD

**Issue by buitrago001** [ISWPOLI/Poli-antifraude#8]
- [x] Identificar requerimientos del sistema (actualizar archivo adjunto requisitos.xlxs)
[Requisitos.xlsx](https://github.com/ISWPOLI/Poli-antifraude/files/802420/Requisitos.xlsx)

**Comment by alejandro995** [comment]
Se realiza parte del documento de requisitos. Se anexa el link: https://docs.google.com/document/d/1C8jA2qjHIXIbyirdlvfVSsCbmXmFsqDzcZJ-5QaK1gI/edit?usp=sharing

**Comment by buitrago001** [comment]
- [x] Revision y actualizacion de requerimientos @alejandro995

**Comment by buitrago001** [comment]
Se completa revisión y se actualiza archivo en el repositorio

https://github.com/ISWPOLI/Poli-antifraude/blob/master/Documentacion/1%20Requerimientos/Documento%20de%20levantamiento%20de%20requerimientos%20V1.pdf
