### ISSUE TITLE
Diagrama de Clases

### ISSUE THREAD

**Issue by alejandro995** [ISWPOLI/Poli-antifraude#84]
- [x] Definicion de clases

- [x] Definicion de de propiedades de las clases

- [x] Definicion de relacion y tipos de clases

**Comment by alejandro995** [comment]
Se definen las clases

**Comment by alejandro995** [comment]
Se termina el documento

**Comment by buitrago001** [comment]
Documento actualizado y cargado en el repositorio

https://github.com/ISWPOLI/Poli-antifraude/blob/master/Documentacion/1%20Requerimientos/Class%20Diagram.png
