### ISSUE TITLE
Estimacion por puntos de fusion 

### ISSUE THREAD

**Issue by alejandro995** [ISWPOLI/Poli-antifraude#87]
- [x] Determinar los tipos de procesos (EO, EQ, EI, ILF, EIF)

- [x] Identificar los items y ficheros por proceso

- [x] Hacer calculo de puntos de fusion sin ajustar

- [x] Hacer calculo de complejidad tecnica

- [x] Hacer calculo de puntos de fusion ajustados

- [x] Estiamcion de hora ezfuerzo y costo de desarrollo

**Comment by sebasc91** [comment]
Se encuentra la estimación por puntos de función

https://github.com/ISWPOLI/Poli-antifraude/blob/master/Documentacion/1%20Requerimientos/Estimaci%C3%B3n%20por%20puntos%20de%20fusi%C3%B3n.pdf
