### ISSUE TITLE
Caracteristica 

### ISSUE THREAD

**Issue by alejandro995** [ISWPOLI/Poli-antifraude#89]
La caracteristica es un desglose de una epica donde se describe una fusion del sistema de manera general.

- [ ]  Se debe tener el cuenta  la estimacion por puntos de fusion para dar un valor real sobre  el tiempo de desarrollo  y  el costo.

**Comment by DiegOliveros** [comment]
@alejandro995  no está estimada:
![image](https://cloud.githubusercontent.com/assets/2998313/25287790/633ab0c4-2688-11e7-9b5c-d36d32bf37cb.png)

**Comment by alejandro995** [comment]
Ese computador no tenia zenhub
