### ISSUE TITLE
4. Modelado de casos de uso.

### ISSUE THREAD

**Issue by buitrago001** [ISWPOLI/Poli-antifraude#9]
- [x] Realizar el modelado de casos de uso + fichas @Basespoli

**Comment by ghost** [comment]
Se realiza Modelado de casos de uso + fichas.

https://github.com/ISWPOLI/Poli-antifraude/blob/master/Documentacion/1%20Requerimientos/4.%20Modelado%20de%20Casos%20de%20Uso%20V1.pdf

**Comment by ghost** [comment]
Se realiza socialización con equipo de trabajo y cierre de tarea.
