### ISSUE TITLE
Login emulador moodle

### ISSUE THREAD

**Issue by buitrago001** [ISWPOLI/Poli-antifraude#96]
Como parte del proceso de pruebas del funcionamiento del sistema antifraude es necesario la creación de un login a un emulador del moodle donde se implementara y probará la funcionalidad del sistema

- [x] Creación de BD para login @sebasc91

- [x] Creación del CSS @sebasc91

- [x] Creación de HTML Vista login @sebasc91

- [x] Creación de HTML Vista Principal @sebasc91

- [x] Creación de HTML Vista Recuperar Contraseña @sebasc91

- [x] Creación de HTML Vista Registro de usuario @sebasc91

- [x] login y validación a la DB del estudiante @sebasc91

**Comment by sebasc91** [comment]
Se encuentra en construcción el sistema de autenticación del usuario

**Comment by sebasc91** [comment]
Se realiza entrega de los archivos correspondientes a la vista login

https://github.com/ISWPOLI/Poli-antifraude/tree/master/Login

**Comment by sebasc91** [comment]
Se entrega login completamente en funcionamiento 

https://github.com/ISWPOLI/Poli-antifraude/tree/master/Login
