### ISSUE TITLE
Base de datos imagenes

### ISSUE THREAD

**Issue by buitrago001** [ISWPOLI/Poli-antifraude#97]
Como parte del proceso y las pruebas que se necesiten en caso de detectar un fraude se requerirá una base de datos que guarde las imagenes durante el semestre correspondiente

**Comment by buitrago001** [comment]
- [x] creación base de datos para guardar las imagenes/fotos

**Comment by ghost** [comment]
Se crea la tabla para el almacenamiento de imágenes de la BBDD  **poliantifraude** se presenta el Script a continuación: 

`CREATE TABLE  `poliantifraude`.`baseFotos` (
`idFoto` INT NOT NULL AUTO_INCREMENT ,
`Codigo` INT NOT NULL COMMENT  'IdEstudiante',
`fotoestudiante` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL ,
PRIMARY KEY (  `idFoto` )
) ENGINE = INNODB CHARACTER SET utf8 COLLATE utf8_general_ci;
`

**Comment by ghost** [comment]
Se indica que el cargue de imágenes no debe ser por File si no por el Pach ya que la base estaria sobrecargada y el Bakup normalizado contendría mucho peso.
